### ISSUE TITLE
Get exception 'Queue empty' when querying partitioned collection with Take

### ISSUE THREAD

**Issue by namkha87** [Azure/azure-documentdb-dotnet#148]
I am using 1.9.5 and I have below code
```
var query = dbClient.CreateDocumentQuery<User>(uri, new FeedOptions()
{
      EnableCrossPartitionQuery = true
});
```
It only happens when I try to use Take on an empty result set
`var result = query.Where(a => a.SearchName.StartsWith("not_found_name")).Take(10).ToList();`
It works fine if there is result returned
`var result = query.Where(a => a.SearchName.StartsWith("found_name")).Take(10).ToList();`
It also works fine if I don't use Take, no exception thrown even the result set is empty
`var result = query.Where(a => a.SearchName.StartsWith("not_found_name")).ToList();`

Stack trace:
```
Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Dequeue()
   at Microsoft.Azure.Documents.Query.TopOrderByChildDocumentQueryExecutionContext.<TakeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Query.TopOrderByDocumentQueryExecutionContext.<ExecuteInternalAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.<ExecuteNextAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<ExecuteAllAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<GetEnumeratorTAsync>d__b.MoveNext()
```

**Comment by namkha87** [comment]
any update on this?

**Comment by jayantacs** [comment]
Hi namkha87, 

Thanks for reporting this. We have identified and fixed the issue. The fix will be rolled out in the next SDK update. 

Jayanta

@rnagpal

**Comment by rnagpal** [comment]
@namkha87 This has been fixed and released as part of .NET SDK 1.10.0
