### ISSUE TITLE
BadImageFormatException

### ISSUE THREAD

**Issue by bret-fynewever** [Azure/azure-documentdb-dotnet#158]
I'm receiving a BadImageFormatException when attempting to exercise the DocumentDB .NET SDK via a Visual Studio unit test method--stack trace is below.  I've wrapped the DocumentDB functionality in a separate assembly.
Targeting .NET Framework 4.6.1 and Microsoft.Azure.DocumentDB version 1.10.0 via NuGet.
The exception occurs on a call to IDocumentQuery.ExecuteNextAsync.
Any help would be greatly appreciated.

Result StackTrace:	
at Microsoft.Azure.Documents.ServiceInteropWrapper.CreateServiceProvider(String configJsonString, IntPtr& serviceProvider)
   at Microsoft.Azure.Documents.Query.QueryPartitionProvider.InitializeServiceProvider()
   at Microsoft.Azure.Documents.Query.QueryPartitionProvider.GetPartitionedQueryExecutionInfo(SqlQuerySpec querySpec, PartitionKeyDefinition partitionKeyDefinition)
   at Microsoft.Azure.Documents.Routing.PartitionRoutingHelper.GetProvidedPartitionKeyRanges(SqlQuerySpec querySpec, Boolean enableCrossPartitionQuery, Boolean parallelizeCrossPartitionQuery, PartitionKeyDefinition partitionKeyDefinition, QueryPartitionProvider queryPartitionProvider, String clientApiVersion, QueryInfo& queryInfo)
   at Microsoft.Azure.Documents.Query.DefaultDocumentQueryExecutionContext.<TryGetTargetPartitionKeyRangeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.Documents.Query.DefaultDocumentQueryExecutionContext.<ExecuteOnceAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2.<<ExecuteAsync>b__1>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.<ExecuteWithRetryPolicy>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Query.DefaultDocumentQueryExecutionContext.<ExecuteInternalAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.<ExecuteNextAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<ExecuteNextPrivateAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XXXXXX.YYYYYY.Core.DocumentServices.BaseDocumentService`1.<GetAsync>d__7.MoveNext() in C:\Users\bretfynewever\OneDrive\Projects\XXXXXX\XXXXXX-YYYYYY-chiller-dashboard\XXXXXX.YYYYYY.Core\DocumentServices\BaseDocumentService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XXXXXX.YYYYYY.Core.DocumentServices.BaseDocumentService`1.<GetAllAsync>d__8.MoveNext() in C:\Users\bretfynewever\OneDrive\Projects\XXXXXX\XXXXXX-YYYYYY-chiller-dashboard\XXXXXX.YYYYYY.Core\DocumentServices\BaseDocumentService.cs:line 0
 --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at XXXXXX.YYYYYY.Core.Tests.ChillerReportTest.Test_GetAll() in C:\Users\bretfynewever\OneDrive\Projects\XXXXXX\XXXXXX-YYYYYY-chiller-dashboard\XXXXXX.YYYYYY.Core.Tests\ChillerReportTest.cs:line 22
Result Message:	
Test method XXXXXX.YYYYYY.Core.Tests.ChillerReportTest.Test_GetAll threw exception: 
System.AggregateException: One or more errors occurred. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

**Comment by bret-fynewever** [comment]
I stumbled across this issue https://github.com/Azure/azure-documentdb-dotnet/issues/140, and it provided direction for resolving the problem I was having.  As long as I set the Default Processor Architecture for the Visual Studio Test Runner to x64 (Test -> Test Settings -> Default Processor Architecture -> x64), then the unit test works.

**Comment by rnagpal** [comment]
Yes, we ship x64 version of the native dlls. So the host process needs to be 64 bit.

**Comment by rnagpal** [comment]
@bret-fynewever With the 1.11.3 release of the SDK having architecture as x86 works now though x64 architecture is recommended for improved performance.

**Comment by bret-fynewever** [comment]
@rnagpal Thanks for the update!

**Comment by Jose-CF** [comment]
Hello,

I build a really tiny application on x64. Still getting the BadImageFormatException. Any work arounds?! Using Microsoft.ServiceFabric 5.6.220
