### ISSUE TITLE
Deserialization Error with Point

### ISSUE THREAD

**Issue by morganabel** [Azure/azure-documentdb-dotnet#186]
I serialized a c# class that has a GeoJson Point as a property of the class. I cannot deserialize it with Json.NET. It fails with a NullReferenceError. Here is the stacktrace:

`at Microsoft.Azure.Documents.Spatial.Converters.GeometryJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TiptWebAppFinal.Models.Processors.BaseQueueProcessor`1.<ReadNextTags>d__3.MoveNext() in C:\Users\morga\Source\Repos\PalitBackend\PalitWebApp\TipWebAppFinal\Models\Processors\BaseQueueProcessor.cs:line 68`

**Comment by morganabel** [comment]
This was a serialization error which was my fault. I was using custom JsonSerializer settings to remove formatting and not include default values. It caused Point to be serialized incorrectly which led to the deserialization problems.

**Comment by rnagpal** [comment]
@morganabel DocumentDB doesn't yet support passing custom serializer settings unless they are set globally. Can you paste the code how you are using it in the DocumentDB context?
