### ISSUE TITLE
DocumentDB Emulator - Creating DB, Collections and stored procedures with SdK does not work

### ISSUE THREAD

**Issue by romeelk** [Azure/azure-documentdb-dotnet#215]
I am using latest DocumentDB  sdk to create locally the following against the DocDB emulator:

- Database
- Collection
- Stored Procs 

Why do i receive the following error intermittently: 
DocDBTrace Error: 0 : Operation will NOT be retried. Current attempt 0, Exception: Microsoft.Azure.Documents.DocumentClientException: Message: {"Errors":["Resource Not Found"]}
ActivityId: f018beef-86c5-47d4-849d-ab06073dbe6e, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/

This seems to happen randomly when creating the database. Sometimes it completes with no error but then sometimes it continuously logs this in the doc db trace output!!

What is even more bizarre is that it completes the process of creating a db and collection and adds the stored procedures. However when I run some of our tests from our API to pull data from the Emulator i receive 500 errors.

If I reset the data and manually create the collection it works ok?

**Comment by nftw** [comment]
I'm also seeing this behaviour, particularly on tests that create databases or collections.

**Comment by leolorenzoluis** [comment]
I'm also getting this behavior when creating from code.

**Comment by nftw** [comment]
I found the issue - I was missing an `await` when calling the CreateDocumentCollectionIfNotExistsAsync helper method. @romeelk @leolorenzoluis check you're not doing something similar (e.g. in CreateDatabaseIfNotExistsAsync), as that could account for the intermittent behaviour you're experiencing.

**Comment by Zing22** [comment]
Same problem here. `await` is not helpful. BTW, I got the same _Request URI_ : `/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/`

**Comment by Mauzer93** [comment]
I am having the same problem and I am correctly awaiting the async method... Does anyone has a solution for this?

**Comment by rnagpal** [comment]
What's the version of the emulator you are using? 

Can you share the code that throws this error?

**Comment by rnagpal** [comment]
Please follow the steps in https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#trace-files to collect the trace files and send that to us. Also a sample app reproing this issue would be great for us to debug the issue faster.

**Comment by Mauzer93** [comment]
After uninstalling the old DocumentDB emulator and resetting the data the problems seems be gone.

**Comment by grahamehorner** [comment]
I'm seeing the same issue running the docker image?

**Comment by FelschR** [comment]
I have this issue in my AppVeyor build (where I download the most recent Emulator for each build).
On my local machine it's running without issues (also with the latest Emulator).

**Comment by tank104** [comment]
I am getting this issue too - **only** when building with Azure Devops - runs fine locally.
This is the code:
```
    PartitionKeyDefinition partitionKey = new PartitionKeyDefinition { Paths = new Collection<string> { PartitionKey } };
      DocumentCollection collection = new DocumentCollection { Id = _collectionId, PartitionKey = partitionKey };
      collection = await _client.CreateDocumentCollectionIfNotExistsAsync(database.SelfLink, collection);
```

and the error:

```
Microsoft.Azure.Documents.DocumentClientException : Message: {"Errors":["Resource Not Found"]}
ActivityId: 2e5329c2-06d5-4068-a573-87b626c2358e, Request URI: /apps/DocDbApp/services/DocDbServer5/partitions/a4cb4951-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats:
RequestStartTime: 2020-06-23T07:35:51.7812774Z, RequestEndTime: 2020-06-23T07:35:54.4450572Z,  Number of regions attempted:1
ResponseTime: 2020-06-23T07:35:52.8205690Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer5/partitions/a4cb4951-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 1, GlobalCommittedLsn: -1, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 449, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: , UsingLocalLSN: False, TransportException: null, ResourceType: BatchApply, OperationType: BatchApply
ResponseTime: 2020-06-23T07:35:52.8595952Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer5/partitions/a4cb4951-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 1, GlobalCommittedLsn: -1, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 449, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: , UsingLocalLSN: False, TransportException: null, ResourceType: BatchApply, OperationType: BatchApply
ResponseTime: 2020-06-23T07:35:54.4450572Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer5/partitions/a4cb4951-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 4, GlobalCommittedLsn: -1, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 45.38, ItemLSN: -1, SessionToken: -1#4, UsingLocalLSN: False, TransportException: null, ResourceType: BatchApply, OperationType: BatchApply
, SDK: Microsoft.Azure.Documents.Common/2.11.0, Windows/10.0.17763 documentdb-netcore-sdk/2.2.2
```

Stack trace:

```
at Microsoft.Azure.Documents.Client.ClientExtensions.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, Boolean throwOnKnownClientErrorCodes)
at Microsoft.Azure.Documents.GatewayStoreModel.<>c__DisplayClass20_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass1_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteAsync(Func`1 callbackMethod, IRetryPolicy retryPolicy, CancellationToken cancellationToken, Action`1 preRetryCallback)
at Microsoft.Azure.Documents.GatewayStoreModel.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, CancellationToken cancellationToken)
at Microsoft.Azure.Documents.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
at Microsoft.Azure.Documents.Client.DocumentClient.CreateAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
at Microsoft.Azure.Documents.Client.DocumentClient.CreateDocumentCollectionPrivateAsync(String databaseLink, DocumentCollection documentCollection, RequestOptions options, IDocumentClientRetryPolicy retryPolicyInstance)
at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass1_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteAsync(Func`1 callbackMethod, IRetryPolicy retryPolicy, CancellationToken cancellationToken, Action`1 preRetryCallback)
at Microsoft.Azure.Documents.Client.DocumentClient.CreateDocumentCollectionIfNotExistsPrivateAsync(String databaseLink, DocumentCollection documentCollection, RequestOptions options)
```

**Comment by tank104** [comment]
It seems to be when there are a certain amount of tests running - I create a new database and collection for each test, so perhaps there is some limit hit, and the error is misleading?
