### ISSUE TITLE
Error upon calling ExecuteNextAsync in v1.14.0 in Azure App Services

### ISSUE THREAD

**Issue by hghansen** [Azure/azure-documentdb-dotnet#259]
With the 1.14.0 of Microsoft.Azure.Documents.Client.dll I have been unable to make calls to  IDocumentQuery<T>.ExecuteNextAsync<T> after deploying my Web Api to Azure App Services.

When running my Web Api from localhost it works just fine, but not in Azure. Reverting to the 1.13.4 dll fixes the problem.

I've attached what the eventlog says.

[Microsoft.Azure.Documents.Client-error.txt](https://github.com/Azure/azure-documentdb-dotnet/files/1002334/Microsoft.Azure.Documents.Client-error.txt)

**Comment by jkonecki** [comment]
I have exactly the same problem when running in Azure Cloud Service:

http://stackoverflow.com/questions/43985540/documentdb-client-1-14-kills-running-process

**Comment by jkonecki** [comment]
I've run into another related problem: when running DocumendDB client 1.13.4 against the latest local emulator I get the following exception:

```
Newtonsoft.Json.JsonReaderException
{"Unexpected character encountered while parsing value: ≻. Path '', line 0, position 0."}
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Azure.Documents.Query.QueryPartitionProvider.GetPartitionedQueryExecutionInfoInternal(SqlQuerySpec querySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected)
   at Microsoft.Azure.Documents.Routing.PartitionRoutingHelper.GetProvidedPartitionKeyRanges(SqlQuerySpec querySpec, Boolean enableCrossPartitionQuery, Boolean parallelizeCrossPartitionQuery, Boolean isContinuationExpected, PartitionKeyDefinition partitionKeyDefinition, QueryPartitionProvider queryPartitionProvider, String clientApiVersion, QueryInfo& queryInfo)
   at Microsoft.Azure.Documents.Query.DefaultDocumentQueryExecutionContext.<TryGetTargetPartitionKeyRangeAsync>d__1e.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Query.DefaultDocumentQueryExecutionContext.<ExecuteOnceAsync>d__a.MoveNext()
```

Clearly there has been a breaking change in handling **partition keys**.

**Comment by hghansen** [comment]
I have also seen that JsonReadException (with 1.13.4 client). Also happens when connecting to Cosmos DB in Azure.

**Comment by vip32** [comment]
happens to me when ddb used inside an azure webjob, locally it runs fine

**Comment by kieronlanning** [comment]
Me too.

**Comment by kieronlanning** [comment]
Three days of issues, compounded by the West Europe outage, and going via Premium Support. 

We eventually found this. 

This is a breaking release - it should be fixed or pulled. At least acknowledged.

**Comment by jkonecki** [comment]
I've got a tweet from DocDB team a few days ago stating that they are
"actively looking" into it.

**Comment by arramac** [comment]
To summarize, we identified a critical issue in the .NET SDK v1.14.0 release on x64 machines that dont support SSE4 instructions. We are working on a patch, but meanwhile please use https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/1.13.4 or earlier. We will post an update when a patch is available.

We have posted an advisory on Twitter.

**Comment by jkonecki** [comment]
Could you please include the link to the tweet? I can't find any related
tweet under @DocumentDB handle.

**Comment by arramac** [comment]
https://twitter.com/AzureCosmosDB/status/866341263955550208

**Comment by arramac** [comment]
@jkonecki and others - can you please test https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/1.14.1

We believe this addresses the issue, but would like to validate that this covers all cases.

**Comment by codecadwallader** [comment]
This seems to have fixed the original erroring use case (Azure WebJob would fail on first call to database) but I'm seeing a new issue where new logins are failing (Azure Website).  I'm debugging and will update this as I know more.. but wanted to put it out quick for anyone else experimenting.

**Comment by jkonecki** [comment]
I can confirm te original issue has been solved for me. I haven't experienced the problem reported by @codecadwallader

**Comment by arramac** [comment]
@codecadwallader let's follow up on a new Github issue for the problem you reported. Closing this one.

**Comment by arramac** [comment]
@codecadwallader  https://github.com/Azure/azure-documentdb-dotnet/issues/267
