### ISSUE TITLE
Timeout with DocumentDB Emulator via MongoClient

### ISSUE THREAD

**Issue by oenayet** [Azure/azure-documentdb-dotnet#263]
I would like a help on an issue.

I'm having trouble connecting to the DocumentDB Emulator via the MongoClient.

**I get the following exception:**
A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = ReadPreferenceServerSelector{ ReadPreference = { Mode : Primary } }, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/localhost:10251" }", EndPoint: "Unspecified/localhost:10251", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:10251
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.<ConnectAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.<CreateStreamAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MongoDB.Driver.Core.Connections.SslStreamFactory.<CreateStreamAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MongoDB.Driver.Core.Connections.BinaryConnection.<OpenHelperAsync>d__48.MoveNext()
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.<OpenHelperAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MongoDB.Driver.Core.Servers.ServerMonitor.<HeartbeatAsync>d__27.MoveNext()" }] }.

**I started the DocumentDBEmulator using the following command:**
DocumentDB.Emulator.exe /MongoPort=10251

**I tried the following connection strings:**
mongodb://localhost:C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==@192.168.111.1:10251/admin?ssl=true&3t.sslSelfSignedCerts=true

or

mongodb://localhost:C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==@localhost:10251/admin?ssl=true&3t.sslSelfSignedCerts=true

**This is the code i use to create the MongoClient:**
            MongoClientSettings settings = MongoClientSettings.FromUrl(
  new MongoUrl(connectionString)
);
            settings.UseSsl = true;
            settings.SslSettings = new SslSettings() { EnabledSslProtocols = SslProtocols.Tls12 };
            var client = new MongoClient(settings);

**Below are the netstat results while connecting:**
C:\Program Files\DocumentDB Emulator>netstat -noab | find "10251"
  TCP    127.0.0.1:59799        127.0.0.1:10251        SYN_SENT        23908
  TCP    192.168.111.1:10251    0.0.0.0:0              LISTENING       22752

**Comment by oenayet** [comment]
Same result when using the default port for MnogoDB connection: 10250, no process is listening on this port at all.

**Comment by ealsur** [comment]
I was successful with just the connection string in the constructor:

    var client = new MongoClient("mongodb://localhost:C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==@localhost:10250/admin?ssl=true&3t.sslSelfSignedCerts=true");

No other settings afterwards.
Can you give it a try?

**Comment by oenayet** [comment]
@ealsur  Same issue. The problem is that no process is listening to port 10250 at all, while the documentdb emulator should listen to this port to take mongodb requests. I have no idea why is this !

**Comment by ealsur** [comment]
Does the emulator UI (not Mongo) work? Can you create/navigate collections and do queries?

**Comment by oenayet** [comment]
@ealsur  yes the emulator works and also accessing it using the documentdb API works as well. Only the MongoDB interface is not working.

**Comment by AndrewHoh** [comment]
@oenayet Hi, can you quickly test and see if port 10255 works?

**Comment by oenayet** [comment]
@AndrewHoh  Port 10255 is not being listened to by any process as well, like 10250.

**Comment by ealsur** [comment]
@oenayet Can you try updating the Emulator to the latest version? There was an update last friday that should solve your issue.
