### ISSUE TITLE
DivideByZeroException

### ISSUE THREAD

**Issue by SqlAdmin** [Azure/azure-documentdb-dotnet#266]
I'm trying to do a benchmark test, it while running I can see an error DivideByZeroException.

System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at DocumentDBBenchmark.Program.Main(String[] args) in C:\Users\bhuvi\azure-documentdb-dotnet\samples\documentdb-benchmark\Program.cs:line 86

Inner Exception 1:
DivideByZeroException: Attempted to divide by zero.

**Comment by SqlAdmin** [comment]
Ok, I found it, its due to No.of tasks.
