### ISSUE TITLE
Unknown error (0xffffffff)

### ISSUE THREAD

**Issue by KhuongNtrd** [Azure/azure-documentdb-dotnet#334]
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()

**Comment by kirankumarkolli** [comment]
@KhuongNtrd  is this the full stack? Also is this transient failure still happening?
