### ISSUE TITLE
Uncatchable DocumentClientException (429 "Request rate is large") in DocumentDB library for .net

### ISSUE THREAD

**Issue by glooydatonnookanthegs** [Azure/azure-documentdb-dotnet#401]
When hitting the emulator rate limit the DocumentDB library throws and uncatchable DocumentClientException for http status code 429.

Message:
```
Microsoft.Azure.Documents.DocumentClientException: 'Message: {"Errors":["Request rate is large"]}
ActivityId: a0653757-d05e-49c5-b4ba-1811db878535, Request URI: /apps/DocDbApp/services/DocDbServer17/partitions/a4cb495d-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: , SDK: Microsoft.Azure.Documents.Common/1.19.102.5'
```

StackTrace: 
```
   at Microsoft.Azure.Documents.Client.ClientExtensions.<ParseResponseAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.Documents.GatewayStoreModel.<>c__DisplayClass10.<<InvokeAsync>b__f>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2.<<ExecuteAsync>b__0>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteAsync>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.GatewayStoreModel.<InvokeAsync>d__1f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.GatewayStoreModel.<ProcessMessageAsync>d__2.MoveNext()
```
using nuget `Microsoft.Azure.DocumentDB version 1.19.1`

The code I'm using:
```csharp
Uri CosmosAddress = new Uri("https://localhost:8081");
string CosmosAuthenticationKey = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";
string CosmosDatabaseName = "DATABASE_NAME";
string CosmosCollectionName = "COLLECTION_NAME";

DocumentClient client = new DocumentClient(
     CosmosAddress,
     CosmosAuthenticationKey,
     new ConnectionPolicy
     {
         EnableEndpointDiscovery = false,
         RetryOptions = new RetryOptions
         {
             MaxRetryAttemptsOnThrottledRequests = 1, // force throttle
             MaxRetryWaitTimeInSeconds = 1
         },
     }
 );

MyClass documenToInsert = new MyClass();
documenToInsert.MyField = "some very long string to force throttle";

for (int i = 0; i <= 9999; i++)
{
    Document inserted;
    Task<ResourceResponse<Document>> insertTask;
    try
    {
        insertTask = client.CreateDocumentAsync
        (
            UriFactory.CreateDocumentCollectionUri
            (
                CosmosDatabaseName,
                CosmosCollectionName
            ),
            traceItem
        );
        inserted = await insertTask;
        if (insertTask.Exception != null)
        {
            // never hits, Exception is always null
        }
    }
    catch (DocumentClientException dce)
    //when (dce.Error.Code == HttpRequestTooLargeErrorCode)
    {
        // never gets hit
    }
}
```

When running the code in visual studio the `DocumentClientException` does blow up in my face but
I can't catch the Exception to force a retry on the insertion. Using the built in retry I can decrease the odds of this happening but I can't avoid it.

**Comment by kirankumarkolli** [comment]
@khdang please look into this.

**Comment by Liversage** [comment]
The line

    inserted = await insertTask;

will throw any exception raised by the task. This means the following code

    if (insertTask.Exception != null)
    {
        // never hits, Exception is always null
    }

is only ever hit if there was no exception thrown in the task. The comment `// never hits, Exception is always null` is true but not surprising.

And because the `await insertTask` is inside a try-catch any `DocumentClientException` thrown is caught.

However, from my own testing the value of `dce.StatusCode` when caught is `NotFound` and `dce.Error.Message` is:

```Message: {"Errors":["Owner resource does not exist"]}
ActivityId: 5f45448a-7515-48b8-ab99-bdafbdd08e5a, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: 
ResponseTime: 2018-01-04T10:16:28.6312697Z, StoreReadResult: StorePhysicalAddress: rntbd://172.27.125.177:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 1398, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 0, IsGone: False, IsNotFound: True, RequestCharge: 1, ItemLSN: -1, ResourceType: Collection, OperationType: Read
ResponseTime: 2018-01-04T10:16:28.6312697Z, StoreReadResult: StorePhysicalAddress: rntbd://172.27.125.177:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 1398, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 0, IsGone: False, IsNotFound: True, RequestCharge: 1, ItemLSN: -1, ResourceType: Collection, OperationType: Read
, SDK: Microsoft.Azure.Documents.Common/1.19.102.5
```

I'm not sure what to make of this but I would certainly expect `dce.StatusCode` to be `429` and not `404` when you are getting throttled.

**Comment by glooydatonnookanthegs** [comment]
When I run it i'm still getting a `429`, not a 404.

```
try
{
    inserted = await insertTask;
    if (insertTask.Exception != null)
    {
        // never hits, Exception is always null
    }
catch (Exception dce)
{
     // never hits, no catchable Exception catchable
     Assert.Fail();
}
```
Any Exception thrown by `inserted = await insertTask;` should be caught, but it isn't.
I can see the Exception in my visual studio, but not in my code.

**Comment by Liversage** [comment]
@glooydatonnookanthegs That's odd. I took your code and ran it with just few modifications to make it compile and it performed as I expected (except for the 404 instead of the 429). Exceptions are certainly being caught as they are supposed to.

There is no such thing as "uncatchable exceptions" in .NET. An exception like `ThreadAbortException` will be rethrown in the `catch` making it sort of "uncatchable" but you can still catch it and log it, just not stop it from propagating.

**Comment by glooydatonnookanthegs** [comment]
@Liversage 
I created a screenshot of what I'm seeing: https://i.imgur.com/dAwDTnB.png
It's not throwing the Exception correctly, otherwise it would mark the like where it is being Thrown in visual studio.
I added a WriteLine and some colourful markings.
Other Exceptions that are uncatchable are OutOfMemoryException & StackOverFlowException, so maybe this one is uncatchable?

**Comment by glooydatonnookanthegs** [comment]
If I set `MaxRetryAttemptsOnThrottledRequests = 0` It throws the exception in a way that I can catch it.
But that's not advisable in production.

**Comment by skram-softheme** [comment]
Hm, looks like retry policy is handling 429 exception, so you would catch it only if retry fails also.
