### ISSUE TITLE
JsonReaderException when there quotes in grouping property

### ISSUE THREAD

**Issue by burikella** [Azure/azure-documentdb-dotnet#405]
Repro sample contains single vertex with quote character (U+0022):
`g.addV('label').property('value', 'Value with " quote')`
Then try to group set containing this vertex by that property with quotation mark:
`g.V("f13bea10-0e54-47b4-9c67-43aee5616348").group().by('value')`

This causes exception:
```
Newtonsoft.Json.JsonReaderException: Invalid character after parsing property name. Expected ':' but got: q. Path '[0]', line 1, position 16.
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JArray.Parse(String json, JsonLoadSettings settings)
   at Microsoft.Azure.Graphs.GremlinDocumentQuery`1.ParseQueryResponse[TResult](String rawReponse, Int32& count)
   at Microsoft.Azure.Graphs.GremlinDocumentQuery`1.<ExecuteNextAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Graphs.GremlinDocumentQuery`1.<ExecuteNextAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Portal.PlatformProxy.Graph.Controllers.GremlinQueriesController.<SubmitQueryAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Portal.PlatformProxy.Graph.Controllers.GremlinQueriesController.<Post>d__0.MoveNext()
```

**Comment by olivertowers** [comment]
I have confirmed that this is a bug related to GraphSON serialization where the property name isn't escaped correctly on `Map` types. `Map` is the GraphSON structure that is used to represent results for group().by() operations.

A fix will be available in the next release of Microsoft.Azure.Graphs.

A possible workaround is to add a literal escape character to the  string value, to ensure that the  GraphSON result is a valid json property name.
For example, this will write the property value as `Value with \" quote`

    g.addV('label').property('value', 'Value with \\" quote')

Thanks for reporting this issue.

**Comment by olivertowers** [comment]
Sorry for the lengthy delay with replying to this.

This bug has been fixed for CosmosDB Gremlin Server. Microsoft.Azure.Graphs is being discontinued so please use Gremlin.NET or another gremlin client driver to connect to your '***.gremlin.cosmosdb.azure.com' endpoint.
