### ISSUE TITLE
Cannot query data after it's written to Table

### ISSUE THREAD

**Issue by mayerc-MSFT** [Azure/azure-documentdb-dotnet#476]
I get the following exception (see below) when I query my table after writing a couple rows to it.

1. Start with a blank table
2. Query -- no results come back, as expected.
3. Insert rows
4. Query again. **Fail.**

I insert rows with 
```
            var batch = new TableBatchOperation();
            foreach (var room in job.Rooms)
            {
                batch.InsertOrReplace(EntityFromModel(room));
            }

            var results = await conferenceRoomsTable.ExecuteBatchAsync(batch);
```

and query with
```
            // Query all rows that belong to the tenant's partition.
            var rangeQuery = new TableQuery<ConferenceRoomEntity>().Where(
                TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, tenantId));
            rangeQuery.TakeCount = 50;

            // Page through the results.
            TableContinuationToken token = null;
            do
            {
                var batchToDelete = new TableBatchOperation();

                // Query next batch.
                var segment = await table.ExecuteQuerySegmentedAsync(rangeQuery, token);
                foreach (var room in segment)
                {
                    batchToDelete.Delete(room);
                }

                // Delete batch.
                if (batchToDelete.Count > 0)
                {
                    await table.ExecuteBatchAsync(batchToDelete);
                }

                // Move to next batch.
                token = segment.ContinuationToken;
            }
            while (token != null);

```
code fails at await table.ExecuteQuerySegmentedAsync

```
System.FormatException: Value is expected to be an object instead it was 'String'.
   at Microsoft.Azure.Documents.Interop.Common.Schema.Edm.TableEntityReader.ThrowFormatException(String format, Object[] args) in d:\dbs\sh\aplrc\0321_175929\cmd\26\Product\Microsoft.Azure.Documents\Interop\Common\Schema\Edm\TableEntityReader.cs:line 436
   at Microsoft.Azure.Documents.Interop.Common.Schema.Edm.TableEntityReader.MoveNext() in d:\dbs\sh\aplrc\0321_175929\cmd\26\Product\Microsoft.Azure.Documents\Interop\Common\Schema\Edm\TableEntityReader.cs:line 142
   at Microsoft.Azure.CosmosDB.Table.EdmConverter.GetPropertiesFromDocument(IList`1 selectColumns, String serializedDocument, IDictionary`2& entityProperties, IDictionary`2& documentDBProperties) in d:\dbs\sh\aplrc\0321_175929\cmd\26\Product\Microsoft.Azure.Documents\Interop\Common\Schema\Edm\EdmConverter.cs:line 36
   at Microsoft.Azure.CosmosDB.Tables.SharedFiles.EntityTranslator.GetEntityPropertiesFromDocument(Document document, IList`1 selectColumns) in d:\dbs\sh\aplrc\0321_175929\cmd\26\Product\Microsoft.Azure.CosmosDB\Tables\SharedFiles\EntityTranslator.cs:line 141
   at Microsoft.Azure.CosmosDB.Table.Extensions.TableExtensionQueryHelper.<QueryDocumentsAsync>d__2`1.MoveNext() in d:\dbs\sh\aplrc\0321_175929\cmd\26\Product\SDK\Table\.net\Lib\WindowsDesktop.Split\Table\Extensions\TableExtensionQueryHelper.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.CosmosDB.Table.Extensions.TableExtensionRetryPolicy.<ExecuteUnderRetryPolicy>d__1`1.MoveNext() in d:\dbs\sh\aplrc\0321_175929\cmd\26\Product\SDK\Table\.net\Lib\WindowsDesktop.Split\Table\Extensions\TableExtensionRetryPolicy.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.CosmosDB.Table.Extensions.TableExtensionExecutor.EndExecute[TResult](IAsyncResult asyncResult) in d:\dbs\sh\aplrc\0321_175929\cmd\26\Product\SDK\Table\.net\Lib\WindowsDesktop.Split\Table\Extensions\TableExtensionExecutor.cs:line 80
   at Microsoft.Azure.CosmosDB.Table.CloudTable.EndExecuteQuerySegmented[TResult](IAsyncResult asyncResult) in d:\dbs\sh\aplrc\0321_175929\cmd\26\Product\SDK\Table\.net\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 655
   at Microsoft.Azure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass2_0`1.<CreateCallback>b__0(IAsyncResult ar) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-common\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Kobe.WebJob.ConferenceRooms.BulkImporter.<ResetConferenceRoomsInTenant>d__3.MoveNext() in E:\repos\Kobe\Kobe.WebJob\ConferenceRooms\BulkImporter.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Kobe.WebJob.ConferenceRooms.BulkImporter.<Import>d__1.MoveNext() in E:\repos\Kobe\Kobe.WebJob\ConferenceRooms\BulkImporter.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---

```

Packages
```
<packages>
  <package id="Microsoft.Azure.CosmosDB.Table" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.Azure.DocumentDB" version="1.21.1" targetFramework="net462" />
  <package id="Microsoft.Azure.Storage.Common" version="9.0.0.1-preview" targetFramework="net462" />
  <package id="Microsoft.Data.Edm" version="5.8.3" targetFramework="net462" />
  <package id="Microsoft.Data.OData" version="5.8.3" targetFramework="net462" />
  <package id="Microsoft.Data.Services.Client" version="5.8.3" targetFramework="net462" />
  <package id="Microsoft.OData.Core" version="7.4.4" targetFramework="net462" />
  <package id="Microsoft.OData.Edm" version="7.4.4" targetFramework="net462" />
  <package id="Microsoft.Spatial" version="7.4.4" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net462" />
  <package id="System.Spatial" version="5.8.3" targetFramework="net462" />
  <package id="WindowsAzure.Storage" version="8.5.0" targetFramework="net462" />
</packages>
```

**Comment by vivekr20** [comment]
(+@ausfeldt who can follow-up with more context if needed)

Hi @mayerc-MSFT,

We're suspecting that tenantId is a guid, and that you've got the wrong overload of GenerateFilterCondition, which is messing up the Odata converter.

If it is indeed a guid. Can you please use GenerateFilterConditionForGuid instead and try?

Thanks,

**Comment by ausfeldt** [comment]
Issue is caused by setting the TypeNameHandling in the JsonSerializerSettings. Removing it will fix it.

public static readonly JsonSerializerSettings SerializerSettings = new JsonSerializerSettings
        {
            DateTimeZoneHandling = DateTimeZoneHandling.Utc,
            Converters = new List<JsonConverter> {
                // The order matters, it's important to register the dictionary converters first
                // Because in C#, a dictionary IS a list, so if we reverse the order, dictionaries
                // Will get serialized as lists
                new DictionaryReadConverter(),
                new DictionaryWriteConverter(),
                new ListReadConverter(),
                new ListWriteConverter(),
                new DefaultInterfaceConverter<IUser, User>(),
                new DefaultInterfaceConverter<ITimeBlock, TimeBlock>(),
                new DefaultInterfaceConverter<ITime, Time>()
            },
            **TypeNameHandling = TypeNameHandling.All,**
            NullValueHandling = NullValueHandling.Ignore,
            TypeNameAssemblyFormat = FormatterAssemblyStyle.Simple,
            ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor,
            ReferenceLoopHandling = ReferenceLoopHandling.Ignore
        };

**Comment by mayerc-MSFT** [comment]
@ausfeldt We configure JSON.NET's serializer settings with `TypeNameHandling = TypeNameHandling.All ` globally in our app.  Unfortunately we cannot remove `TypeNameHandling = TypeNameHandling.All` because that'd break deserialization across the board.

It seems the Table API/SDK is re-using our app's global JSON.NET serializer settings under the covers, which ultimately breaks the Table query API.

Could you offer an alternative solution?

For example, could you update the code in the Table SDK _not to use JSON.NET's global serializer settings_? Alternatively, is it possible for a consumer of the Table API SDK to explicitly hand it an instance of serializer settings to use (instead of picking up global settings)?

**Comment by ausfeldt** [comment]
@mayerc-MSFT Added to the backlog. I look into it next week.
