### ISSUE TITLE
ArgumentOutOfRangeException when combineing Model projection with Where-In in linq query

### ISSUE THREAD

**Issue by mmsommer** [Azure/azure-documentdb-dotnet#81]
A *where in*, or *Array.Contains(..)* linq query results in an ArgumentOutOfRangeException when a projection (as in `Select(x => x.projection)`) is used before the where clause.
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Unexpected Sql Scalar expression kind InExpression
```

I expected it to not fail and translate the expression into a *where in* query to Azure Documents.

Test code:
```c#
using System;
using System.Linq;
using Microsoft.Azure.Documents;
using Microsoft.Azure.Documents.Client;
using Microsoft.Azure.Documents.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;

[TestClass]
public class DocumentTests
{
	private DocumentClient _client;
	private Database _database;
	private DocumentCollection _documentCollection;

	[TestInitialize]
	public void Setup()
	{
		_client = new DocumentClient(new Uri("uri"),"secret");
		_database = _client.CreateDatabaseQuery().Where(db => db.Id == "DocumentTesting").AsEnumerable().FirstOrDefault();

		if (_database == null)
		{
			_database = _client.CreateDatabaseAsync(
				new Database
				{
					Id = "DocumentTesting"
				}).Result;
		}

		_documentCollection = _client.CreateDocumentCollectionQuery("dbs/" + _database.Id)
			.Where(c => c.Id == "TestCollection").AsEnumerable()
			.FirstOrDefault();

		if (_documentCollection == null)
		{
			_documentCollection = _client.CreateDocumentCollectionAsync(
				"dbs/" + _database.Id,
				new DocumentCollection
				{
					Id = "TestCollection"
				}).Result;
		}

		var document = _client.CreateDocumentQuery<TestResource>("dbs/" + _database.Id + "/colls/" + _documentCollection.Id)
			.Where(d => d.Name == "foo").AsEnumerable()
			.FirstOrDefault();

		if (document == null)
		{
			document = new TestResource { Name = "foo", Model = new TestModel { Name = "bar" } };

			_client.CreateDocumentAsync("dbs/" + _database.Id + "/colls/" + _documentCollection.Id, document).Wait();
		}
	}

	[TestMethod]
	public void WhereInQuery_WithoutProjection_WithStaticList()
	{
		var result = _client.CreateDocumentQuery<TestResource>(_documentCollection.DocumentsLink)
				.Where(res => new[] { "foo" }.Contains(res.Name))
				.AsEnumerable().ToArray();

		Assert.AreEqual("foo", result.First().Name);
	}

	[TestMethod]
	public void WhereInQuery_WithoutProjection_WithDynamicList()
	{
		var names = new[] { "foo" };
		var result =
			_client.CreateDocumentQuery<TestResource>(_documentCollection.DocumentsLink)
				.Where(res => names.Contains(res.Name))
				.AsEnumerable().ToArray();

		Assert.AreEqual("foo", result.First().Name);
	}

	[TestMethod]
	public void WhereInQuery_WithProjection_WithStaticList()
	{
		var result =
			_client.CreateDocumentQuery<TestResource>(_documentCollection.DocumentsLink)
				.Select(res => res.Model)
				.Where(res => new[] { "bar" }.Contains(res.Name))
				.AsEnumerable().ToArray();

		Assert.AreEqual("bar", result.First().Name);
	}

	[TestMethod]
	// !!! THIS ONE FAILS !!!
	public void WhereInQuery_WithProjection_WithDynamicList()
	{
		var names = new[] { "bar" };
		var result =
			_client.CreateDocumentQuery<TestResource>(_documentCollection.DocumentsLink)
				.Select(res => res.Model)
				.Where(res => names.Contains(res.Name))
				.AsEnumerable().ToArray();

		Assert.AreEqual("bar", result.First().Name);
	}

	private class TestResource : Resource
	{
		public string Name { get; set; }
		public TestModel Model { get; set; }
	}

	private class TestModel
	{
		public string Name { get; set; }
	}
}
```

**Comment by ryancrawcour** [comment]
Confirmed as a problem. Fix has been submitted for review. Will get a new deployment asap.

**Comment by ryancrawcour** [comment]
Should be deployed within the next few days.

**Comment by wis3guy** [comment]
That is great news!

**Comment by ryancrawcour** [comment]
fixed in 1.5.2

**Comment by wis3guy** [comment]
@ryancrawcour We have updated our nuget package to 1.5.2 and reran our tests. Our conclusion is that the provided unit test still fails erroneously.

At this point i'm not sure what is going on. Did the fix not make it into the latest nuget package? Was the bug not understood and was something else fixed?

**Comment by ryancrawcour** [comment]
Here's the unit test we built (derived from the code above) - https://gist.github.com/ryancrawcour/a833cd0f0543fcc9a8a4

This failed first which led us to finding the problem.
It now passes in 1.5.2 after fix was applied. 

Are you able to get the sql statement from the query? Or does it fail before it even gets here?

**Comment by mmsommer** [comment]
I did try to catch a sql statement with Fiddler, but none came through. Apparently it fails before it gets there.

This is the stacktrace I get returned:
```
System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Unexpected Sql Scalar expression kind InExpression
   at Microsoft.Azure.Documents.Linq.SqlExpressionManipulation.Substitute(SqlScalarExpression replacement, SqlIdentifier toReplace, SqlScalarExpression into)
   at Microsoft.Azure.Documents.Linq.QueryUnderConstruction.Substitute(SqlSelectSpec spec, SqlIdentifier inputParam, SqlWhereClause whereClause)
   at Microsoft.Azure.Documents.Linq.QueryUnderConstruction.Flatten()
   at Microsoft.Azure.Documents.Linq.ExpressionToSql.TranslateQuery(Expression inputExpression)
   at Microsoft.Azure.Documents.Linq.SQLTranslator.TranslateQuery(Expression inputExpression)
   at Microsoft.Azure.Documents.Linq.DocumentQueryEvaluator.HandleMethodCallExpression(MethodCallExpression expression)
   at Microsoft.Azure.Documents.Linq.DocumentQueryEvaluator.Evaluate(Expression expression)
   at Microsoft.Azure.Documents.Linq.DocumentQueryExecutionContext.<ExecuteAllAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<GetEnumeratorTAsync>d__10.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DocumentTests.WhereInQuery_WithProjection_WithDynamicList() in C:\Workplace\Gfms\Tns.Nipo.Gfms.Core.Tests\Infrastructure\DocumentTests.cs:line 96
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Unexpected Sql Scalar expression kind InExpression
   at Microsoft.Azure.Documents.Linq.SqlExpressionManipulation.Substitute(SqlScalarExpression replacement, SqlIdentifier toReplace, SqlScalarExpression into)
   at Microsoft.Azure.Documents.Linq.QueryUnderConstruction.Substitute(SqlSelectSpec spec, SqlIdentifier inputParam, SqlWhereClause whereClause)
   at Microsoft.Azure.Documents.Linq.QueryUnderConstruction.Flatten()
   at Microsoft.Azure.Documents.Linq.ExpressionToSql.TranslateQuery(Expression inputExpression)
   at Microsoft.Azure.Documents.Linq.SQLTranslator.TranslateQuery(Expression inputExpression)
   at Microsoft.Azure.Documents.Linq.DocumentQueryEvaluator.HandleMethodCallExpression(MethodCallExpression expression)
   at Microsoft.Azure.Documents.Linq.DocumentQueryEvaluator.Evaluate(Expression expression)
   at Microsoft.Azure.Documents.Linq.DocumentQueryExecutionContext.<ExecuteAllAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<GetEnumeratorTAsync>d__10.MoveNext()<---
```

**Comment by ryancrawcour** [comment]
per email conversation with @mmsommer this is now working. closing the issue as resolved.
